import { useCallback, useEffect, useState } from 'react'

/** 경량 i18n — 설정 팝업에서 바꾼 언어(localStorage 'lang')에 따라 UI 문구를 전환한다.
 * 언어 변경 시 SettingsModal이 window 'langchange' 이벤트를 쏘면 useLang 구독자가 갱신된다. */
export type Lang = 'ko' | 'en'

type Dict = Record<string, string>

const KO: Dict = {
  'nav.gallery': '갤러리',
  'nav.stats': '통계',
  'role.admin': '관리자',
  'role.student': '학생',
  'topbar.settings': '설정',
  'topbar.logout': '로그아웃',
  'topbar.language': '언어 선택',
  'topbar.levelFilter': '레벨 필터',
  'topbar.skillFilter': '게임학습종류 필터',
  'level.all': '전체 레벨',
  'skill.all': '전체 학습',
  'settings.title': '설정',
  'settings.language': '언어',
  'settings.sound': '사운드',
  'settings.viewMode': '갤러리 보기',
  'settings.close': '닫기',
  'view.gallery': '카드형',
  'view.list': '리스트형',
  'gallery.loading': '불러오는 중…',
  'gallery.empty': '아직 게시된 콘텐츠가 없습니다.',
  'gallery.noLevel': '선택한 레벨에 해당하는 게임이 없습니다.',
  'gallery.stale': '스튜디오 연결이 원활하지 않아 마지막으로 확인된 목록을 보여줍니다.',
  'gallery.retry': '다시 시도',
  'gallery.refreshing': '갱신 중…',
  'gallery.prev': '이전',
  'gallery.next': '다음',
  'gallery.page': '{n}페이지',
  'hero.title': '놀이로 키우는 읽기 자신감!',
  'hero.sub': '단계별 파닉스 게임으로 아이의 읽기 잠재력을 열어주세요.',
  'hero.cta': '지금 시작하기',
  'dash.new.title': '이달의 신규 파닉스',
  'dash.new.sub': '새롭게 출시된 재미있는 게임들을 만나보세요.',
  'dash.grid.title': '영역별 맞춤 파닉스 놀이',
  'dash.grid.sub': '우리 아이의 수준에 딱 맞는 게임을 골라보세요.',
  'dash.ranking.title': '이번 주 인기 랭킹',
  'dash.ranking.sub': '친구들이 가장 좋아한 게임은 무엇일까요?',
  'dash.recent.title': '나의 최근 플레이',
  'dash.recent.sub': '최근에 즐긴 게임을 다시 이어서 해보세요.',
  'dash.plays': '{n}회 플레이',
  'dash.lastPlayed': '마지막 플레이: {t}',
  'dash.time.0': '방금 전',
  'dash.time.1': '2시간 전',
  'dash.time.2': '어제',
  'dash.time.3': '3일 전',
  'dash.time.4': '지난주',
  'promo.title': 'POLY Phonics Games',
  'promo.sub': '지금 100개 이상의 게임과 이야기를 무제한으로 즐겨보세요.',
  'footer.aiNotice': '본 콘텐츠는 AI가 생성한 내용을 포함하고 있습니다.',
  'footer.copyright': 'COPYRIGHT © 2026 Poly Inspiration. ALL RIGHTS RESERVED.',
}

const EN: Dict = {
  'nav.gallery': 'Gallery',
  'nav.stats': 'Stats',
  'role.admin': 'Admin',
  'role.student': 'Student',
  'topbar.settings': 'Settings',
  'topbar.logout': 'Log out',
  'topbar.language': 'Language',
  'topbar.levelFilter': 'Level filter',
  'topbar.skillFilter': 'Learning type filter',
  'level.all': 'All levels',
  'skill.all': 'All learning',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.sound': 'Sound',
  'settings.viewMode': 'Gallery view',
  'settings.close': 'Close',
  'view.gallery': 'Cards',
  'view.list': 'List',
  'gallery.loading': 'Loading…',
  'gallery.empty': 'No content has been published yet.',
  'gallery.noLevel': 'No games match the selected level.',
  'gallery.stale': 'Studio connection is unstable — showing the last known list.',
  'gallery.retry': 'Retry',
  'gallery.refreshing': 'Refreshing…',
  'gallery.prev': 'Previous',
  'gallery.next': 'Next',
  'gallery.page': 'Page {n}',
  'hero.title': 'Build Reading Confidence Through Play!',
  'hero.sub': "Step-by-step phonics games designed to unlock your child's reading potential.",
  'hero.cta': 'Get Started Now',
  'dash.new.title': 'New This Month',
  'dash.new.sub': 'Discover the latest fun games just added.',
  'dash.grid.title': 'Phonics Play by Skill',
  'dash.grid.sub': 'Pick a game that fits your child’s level.',
  'dash.ranking.title': 'This Week’s Top Picks',
  'dash.ranking.sub': 'See which games friends loved the most.',
  'dash.recent.title': 'My Recent Plays',
  'dash.recent.sub': 'Jump back into the games you played recently.',
  'dash.plays': '{n} plays',
  'dash.lastPlayed': 'Last played: {t}',
  'dash.time.0': 'Just now',
  'dash.time.1': '2 hours ago',
  'dash.time.2': 'Yesterday',
  'dash.time.3': '3 days ago',
  'dash.time.4': 'Last week',
  'promo.title': 'POLY Phonics Games',
  'promo.sub': 'Unlock unlimited access to 100+ games and stories.',
  'footer.aiNotice': 'This content includes material generated by AI.',
  'footer.copyright': 'COPYRIGHT © 2026 Poly Inspiration. ALL RIGHTS RESERVED.',
}

const DICTS: Record<Lang, Dict> = { ko: KO, en: EN }

export function getLang(): Lang {
  return typeof window !== 'undefined' && localStorage.getItem('lang') === 'en' ? 'en' : 'ko'
}

/** 언어 변경을 알림(설정 팝업에서 호출). */
export function setLang(lang: Lang): void {
  localStorage.setItem('lang', lang)
  window.dispatchEvent(new Event('langchange'))
}

/** 현재 언어를 반환하고, 변경 시 리렌더한다. */
export function useLang(): Lang {
  const [lang, setState] = useState<Lang>(getLang)
  useEffect(() => {
    const onChange = () => setState(getLang())
    window.addEventListener('langchange', onChange)
    window.addEventListener('storage', onChange) // 다른 탭 동기화
    return () => {
      window.removeEventListener('langchange', onChange)
      window.removeEventListener('storage', onChange)
    }
  }, [])
  return lang
}

/** t('key', { n: 3 }) → 현재 언어 문구({n} 치환). 키 없으면 ko 폴백, 그래도 없으면 키 그대로. */
export function useT() {
  const lang = useLang()
  return useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      let s = DICTS[lang][key] ?? KO[key] ?? key
      if (vars) for (const k in vars) s = s.replace(`{${k}}`, String(vars[k]))
      return s
    },
    [lang],
  )
}
